//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int Attendance_ID { get; set; }
        public string Std_GRNO { get; set; }
        public string Class_ID { get; set; }
        public System.DateTime Attendance_Date { get; set; }
        public string Attendance_Status { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Student Student { get; set; }
    }
}
