//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentHead
    {
        public int StudentMarks_ID { get; set; }
        public string Std_GRNO { get; set; }
        public Nullable<int> ClassHead_ID { get; set; }
        public Nullable<int> ObtainedMarks { get; set; }
    
        public virtual ClassHead ClassHead { get; set; }
        public virtual Student Student { get; set; }
    }
}
